# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:r)
variables:
  GO_VERSION: 1.13

jobs:
  - job: BDDTest
    pool:
      vmImage: ubuntu-16.04
    timeoutInMinutes: 30
    steps:
    - template: azp-dependencies.yml
    - checkout: self
    - bash: |
        function logout {
          docker logout
        }
        trap logout EXIT
        echo $DOCKER_PASSWORD | docker login docker.pkg.github.com --username $DOCKER_USER --password-stdin
        make bdd-test
      env:
        DOCKER_USER: $(DOCKER_USER)
        DOCKER_PASSWORD: $(DOCKER_PASSWORD)
      displayName: Run BDD tests

  - job: Checks
    pool:
      vmImage: ubuntu-16.04
    timeoutInMinutes: 10
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - script: make checks
        displayName: Run checks

  - job: Publish
    dependsOn:
      - Checks
      - BDDTest
    condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
    pool:
      vmImage: ubuntu-16.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - bash: |
          function logout {
            docker logout
          }
          trap logout EXIT
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin
          source scripts/build_aries_agent_image.sh
          docker tag aries-framework-go/agent-rest:latest  trustbloc/aries-agent-rest:$AGENT_IMAGE_TAG
          docker push trustbloc/aries-agent-rest:$AGENT_IMAGE_TAG
        env:
          DOCKER_USER: $(DOCKER_USER)
          DOCKER_PASSWORD: $(DOCKER_PASSWORD)
          BASE_VERSION: $(BASE_VERSION)
          IS_RELEASE: $(IS_RELEASE)
          ARIES_REVISION: $(ARIES_REVISION)

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - master
    always: true
